site_name: Esi\LibrariesIO
site_description: 'Documentation for LibrariesIO - A simple API wrapper/client for the Libraries.io API.'
site_author: 'Eric Sizemore'
copyright: 'Copyright (C) 2023-2024 Eric Sizemore'
site_url: https://www.secondversion.com/docs/librariesio
docs_dir: docs/
repo_name: 'ericsizemore/librariesio'
repo_url: 'https://github.com/ericsizemore/librariesio'
theme: readthedocs
nav:
  - Home: 'index.md'
  - About:
    - 'License': 'license.md'
    - 'Changelog': 'changelog.md'
    - 'Security': 'security.md'
    - 'Code of Conduct': 'code-of-conduct.md'
  - Installing: 'installation.md'
  - Basic Usage: 'basic-usage.md'
  - Endpoints:
    - 'Platform': 'platform.md'
    - 'Project': 'project.md'
    - 'Repository': 'repository.md'
    - 'Subscription': 'subscription.md'
    - 'User': 'user.md'
  - Extras
    - 'Utils': 'utils.md'